name: Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  
    

jobs:
  container:
    runs-on: ubuntu-latest
    steps:    
    - uses: actions/checkout@v2    
    - name: Docker Build
      shell: bash
      run: |
        # docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
        docker buildx build . --platform linux/arm64 -t ghcr.io/brandencward/runners-resume:$(date +%Y%m%d.$GITHUB_RUN_NUMBER) -t ghcr.io/brandencward/runners-resume:latest
    - name: Docker Publish
      shell: bash
      run: |
        docker images -a
        echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u brandencward --password-stdin
        docker push -a ghcr.io/brandencward/runners-resume:       
 
